### ISSUE TITLE
Variant Groups + Arbitrary Variants = Doesn't Work

### ISSUE THREAD

**Issue by AaronBeaudoin** [unocss/unocss#1419]
I think this problem is best explained with a dead simple example:

```html
<div class="sm:bg-red-800 sm:text-red-400">Test 1</div>
<div class="sm:(bg-red-800 text-red-400)">Test 2</div>
<div class="[&]:bg-red-800 [&]:text-red-400">Test 3</div>
<div class="[&]:(bg-red-800 text-red-400)">Test 4</div>
```

![image](https://user-images.githubusercontent.com/26592486/184671574-30a64e82-8808-436c-b4bd-489d75d64c0e.png)

Basically, when using Windi [Variant Groups](https://windicss.org/features/variant-groups.html) via [`@unocss/transformer-variant-group`](https://github.com/unocss/unocss/tree/main/packages/transformer-variant-group) in combination with Tailwind's [Arbitrary Variants](https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants) feature/syntax, things seem to stop working. Is this a bug, or is there some limitation that keeps us from doing this?

**Comment by antfu** [comment]
Fixed already by #1415

**Comment by AaronBeaudoin** [comment]
This issue is **not fixed** in v0.45.7, which includes #1415 according to the changelog.

Please see my minimal reproduction [here](https://github.com/AaronBeaudoin/unocss-issue-groups) and kindly re-open the issue if you would.

**Comment by Jurool** [comment]
This problem does exist

**Comment by VladimirCores** [comment]
Its not fixed, "Variant Groups" does not work in `"unocss": "^0.46.0"`
