### ISSUE TITLE
[regression] [VSCode] UnoCSS language server doesen't unload and reload properly

### ISSUE THREAD

**Issue by KraXen72** [unocss/unocss#3194]
### UnoCSS version

0.56.4

### Describe the bug

1. When opening a project or saving the config file (!!!!!!), the unocss language server loads again, without unloading:
![image](https://github.com/unocss/unocss/assets/21956756/02f51fd2-b4b3-4995-90f9-f26bb0dbae75)
it loads progressively more an more instances of itself
![image](https://github.com/unocss/unocss/assets/21956756/b9e08608-5923-4867-bb0a-9312ddbbe40b)

It also doesen't reload & put anything into output when files defined in `configDeps` change, forcing me to trigger reloading by saving config, and causing another instance of the language server

Please, fix this bug soon! it is making it unbearable to work with unocss!! ~~And (as far as i know), you cannot even downgrade the VSCode extension, so i'm stuck with this until it's resolved!~~ Thanks!
EDIT: i found out how to downgrade extension in vscode, but it's still a hassle downgrading all the unocss packages too.

### Reproduction

Cannot reproduce in stackblitz, as it doesen't use the VSCode extension.
I am using a custom preset loaded from an external file, if it helps, but i don't think that's the issue.

### System Info

Windows 10, Sveltekit, UnoCSS 0.56.4

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by KraXen72** [comment]
It works fine on unocss 0.56.2

**Comment by Simon-He95** [comment]
> It works fine on unocss 0.56.2

This problem has been fixed in the next version
related: #3181

**Comment by KraXen72** [comment]
thanks! will re-open if it still is an issue

**Comment by rylanharper** [comment]
I am still experiencing somewhat of an issue with this.. I have to manually refresh VS code to see the plugin's data.. Perhaps its because I have a specific unoroot setting VS code such as this (although this may not be related)
```
"unocss.root": "./web",
```
 > I am working on a Nuxt3 project that uses two folders, one `studio` and another `web`
 
Just checking to see if anyone is still experiencing this? If there are further issues perhaps we can reopen this?

**Comment by Simon-He95** [comment]
> I am still experiencing somewhat of an issue with this.. I have to manually refresh VS code to see the plugin's data.. Perhaps its because I have a specific unoroot setting VS code such as this (although this may not be related)我仍然遇到一些问题。.我必须手动刷新VS代码才能查看插件的数据。也许是因为我有一个特定的 unoroot 设置 VS 代码，例如这样（尽管这可能不相关）
> 
> ```
> "unocss.root": "./web",
> ```
> 
> > I am working on a Nuxt3 project that uses two folders, one `studio` and another `web`我正在处理一个Nuxt3项目，该项目使用两个文件夹，一个 `studio` 文件夹和另一个 `web` 文件夹
> 
> Just checking to see if anyone is still experiencing this? If there are further issues perhaps we can reopen this?只是检查是否有人仍然遇到这种情况？如果还有其他问题，也许我们可以重新打开它？

I think you can remove unocss.root, which should be able to detect changes in uno.config. The new features do not take into account the logic of the original uno.root configuration.

**Comment by rylanharper** [comment]
@Simon-He95 I removed the `unoroot` and it seems to be working now! Thank you for the help on this:)
