### ISSUE TITLE
@unocss/preset-icons broken?

### ISSUE THREAD

**Issue by shirok1** [unocss/unocss#3551]
### UnoCSS version

0.58.4

### Describe the bug

I am using @unocss/nuxt. If `presetIcons()` is in my `uno.config.ts`, the build of `__uno.css` will fail. Directly accessing it will produce following log:

```log
[8:22:48 PM]  ERROR  Internal server error: Error: Cannot find module @iconify-json/simple-icons-x imported from file://[Project Root], file://[Parent of Project Root], file://[Project Root]/_index.js, file://[Parent of Project Root]/node_modules
      at resolvePath (file://[Project Root]/node_modules/mlly/dist/index.mjs:2121:10)
      at task (file://[Project Root]/node_modules/@iconify/utils/lib/loader/fs.mjs:44:31)
      at async loadNodeIcon (file://[Project Root]/node_modules/@iconify/utils/lib/loader/node-loader.mjs:31:19)
      at async [Project Root]/node_modules/@unocss/preset-icons/dist/shared/preset-icons.5PH3fREn.cjs:811:22
      at async rules.layer.layer ([Project Root]/node_modules/@unocss/preset-icons/dist/shared/preset-icons.5PH3fREn.cjs:767:21)
      at async UnoGenerator.parseUtil (file://[Project Root]/node_modules/@unocss/core/dist/index.mjs:948:22)
      at async UnoGenerator.parseToken (file://[Project Root]/node_modules/@unocss/core/dist/index.mjs:682:120)
      at async file://[Project Root]/node_modules/@unocss/core/dist/index.mjs:717:23
      at async Promise.all (index 2798)
      at async UnoGenerator.generate (file://[Project Root]/node_modules/@unocss/core/dist/index.mjs:738:5)
      at async generateCSS (file://[Project Root]/node_modules/@unocss/vite/dist/index.mjs:613:16)
      at async Context.load (file://[Project Root]/node_modules/@unocss/vite/dist/index.mjs:730:31)
      at async file://[Project Root]/node_modules/vite-plugin-inspect/dist/index.mjs:406:17
      at async file://[Project Root]/node_modules/vite-plugin-inspect/dist/index.mjs:406:17
      at async Object.load (file://[Project Root]/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:64034:32)
      at async loadAndTransform (file://[Project Root]/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:49665:24)
      at async warmup (file://[Project Root]/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.RU3bcDTV.mjs:881:7)
      at async Promise.all (index 1)
      at async warmup (file://[Project Root]/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.RU3bcDTV.mjs:891:7)
      at async Promise.all (index 10)
      at async warmup (file://[Project Root]/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.RU3bcDTV.mjs:891:7)
      at async Promise.all (index 6)
      at async warmup (file://[Project Root]/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.RU3bcDTV.mjs:891:7)
      at async Promise.all (index 0)
      at async warmupViteServer (file://[Project Root]/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.RU3bcDTV.mjs:896:3)

```

The reproduction StackBlitz show a similar error, with a different icon instead of `simple-icons-x`.

NOTICE: Downgrading just @unocss/preset-icons to 0.58.3 solve this problem too.

### Reproduction

https://stackblitz.com/~/edit/unocss-unocss-7ukrn3

### System Info

macOS 14.3, Arc browser 1.28.0 (45831), Nuxt, Bun as package manager

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by shirok1** [comment]
Will #3539 be correlated?

**Comment by userquin** [comment]
no, I guess it is about last iconify utils package version https://github.com/iconify/iconify/pull/280#issuecomment-1925607036, try fixing the version to `2.1.20`  in you package.json file: `"@iconify/utils": "2.1.20"` (in your dev dependencies, maybe you'll need to use `resolutions` or another package entries dependending on you package manager, for example "pnpm.overrides")

Can you check `@iconify/utils` version in your application?

Here your reproduction working: https://stackblitz.com/c/edit/unocss-unocss-v79njm?file=package.json

Now the json file is loaded by `mlly`  instead from `local-pkg`, maybe you also need to include some option in tsconfig.json.

**Comment by userquin** [comment]
it seems @cyberalien has found the problem, he's going to release a next version to do some tests later will be fixed and released.

**Comment by userquin** [comment]
should be fixed in new `@iconify/utils` release, update the dependency or use  `^2.1.22`: https://stackblitz.com/c/edit/unocss-unocss-v79njm?file=package.json

**Comment by cyberalien** [comment]
Should be fixed now. Try `@iconify/utils@2.1.22`.

One of `resolvePath` calls in recently updated code was missing error handling, so it threw error.

**Comment by shirok1** [comment]
The problem persisted in my case. I've add `"@iconify/utils": "^2.1.22",` to my devDependencies and I saw below:

```
bun update v1.0.25 (a8ff7be6)

 + @iconify/utils@2.1.22

warn: nuxt-app's postinstall script took 1.6s

 2 packages installed [3.82s]
```

I think this is because `@unocss/preset-icons` have it's own `node_modules`. Should a dependency bump version for `@unocss/preset-icons` released too? Or should some measures be done by me locally?

<img width="323" alt="image" src="https://github.com/unocss/unocss/assets/12044683/1b673faa-0760-4c10-9a1d-bd106f44db1c">

**Comment by cyberalien** [comment]
Can you create a reproduction?

**Comment by userquin** [comment]
try `"resolutions": { "@iconify/utils": "2.1.22" }` (remove dev dependency, we need to update unocss)

**Comment by shirok1** [comment]
Yes, I removed (actually rename) `node_modules` dir inside `@unocss/preset-icons` and it worked.

**Comment by cyberalien** [comment]
phew. so update worked. i'll change it to `latest` tag

**Comment by shirok1** [comment]
> try `"resolutions": { "@iconify/utils": "2.1.22" }` (remove dev dependency, we need to update unocss)

This trick worked too, `@unocss/preset-icons` now don't have its own `node_modules`. Is there a less *hacky* approach for "not having its own `node_modules`"?

**Comment by userquin** [comment]
We cannot solve it, you/we need to use package manager "override" stuff to do this (`override` should work with npm and `resolutions` should work with yarn and pnpm, when using pnpm you can also use `pnpm.overrides`): we can move unocss dependencies to dev dependencies, but then everyone will need to install all unocss dev dependencies on each project, no make sense

**Comment by shirok1** [comment]
I found that I can actually remove `@iconify/utils` and the resolution works. I'll call it a day.
