### ISSUE TITLE
extractorSvelte doesn't work in 'svelte-scoped' mode

### ISSUE THREAD

**Issue by jacob-8** [unocss/unocss#663]
Can be reproduced by adding `mode: 'svelte-scoped'` to the `test/fixtures/sveltekit` example in this repo.

I know the `svelte-scoped` mode is WIP but I'm creating this on the off chance this problem isn't known yet.

A workaround is to place needed classes on a hidden element in the same component, so this will work for now:
```
<div class:bg-red-400={variable}>...</div>
<span class="hidden bg-red-400" />
```

**Comment by antfu** [comment]
IIRC it has been fixed. If not, please create a new issue with a minimal reproduction. Thanks.

**Comment by jacob-8** [comment]
Did a little more looking into this and it is still not fixed. The reason being that 'svelte-scoped' does not hand off the file `id` to the `extractorSvelte` function which only strips `class:` prefixes from files with an `id` ending in `.svelte` as seen in packages/core/src/extractors/svelte.tsL9: `if (id && id.endsWith('.svelte')) {`

I discovered this by logging the `id` and `result` values in the `extractorSvelte` function both with `svelte-scoped` mode and without. I will look at `svelte-scoped` mode now and see if I can understand how to get the `id` being passed into the extractors like normal. If I can't, I will post a minimal reproduction.
