### ISSUE TITLE
ERROR in ./_virtual_\__uno.css 4:14-362 Module not found: Error: Can't resolve '../_virtual_/__uno.css' 

### ISSUE THREAD

**Issue by peterroe** [unocss/unocss#931]
Once I import `uno.css` in `main.ts`:

```ts
import 'uno.css'
```
An error happened:

```shell
ERROR in ./_virtual_\__uno.css 4:14-362
Module not found: Error: Can't resolve '../_virtual_/__uno.css' in '/MyProject/_virtual_\'
```

My deps:

```shell
"@unocss/webpack": "^0.32.12",
"unocss": "^0.30.6",
```

My `webpack.config.js`

```ts
const { defineConfig } = require("@vue/cli-service");
const { presetAttributify, presetUno, presetIcons } = require("unocss");

module.exports = defineConfig({
  transpileDependencies: true,
  chainWebpack: (config) => {
    config.resolve.extensions.add(".ts");
  },
  configureWebpack: {
    resolve: {
      fallback: {
        http: false,
        https: false,
        url: false,
        timers: false,
      },
    },
    plugins: [
      require("unplugin-icons/webpack")({
        autoInstall: true,
      }),
      require("@unocss/webpack").default({
        theme: {
          fontFamily: {
            sans: '"Inter", Inter var,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji',
          },
        },
        presets: [
          presetIcons({
            extraProperties: {
              display: "inline-block",
              height: "1.2em",
              width: "1.2em",
              "vertical-align": "text-bottom",
            },
          }),
          presetAttributify(),
          presetUno(),
        ],
      }),
    ],
  },
  lintOnSave: false,
  pluginOptions: {
    windicss: {
      // see https://github.com/windicss/vite-plugin-windicss/blob/main/packages/plugin-utils/src/options.ts
    },
  },
});

```

**Comment by aliuq** [comment]
In WSL?

**Comment by peterroe** [comment]
No，Macbook pro

**Comment by aliuq** [comment]
> No，Macbook pro

Try to modify `backSlash` function in `node_modules/unplugin/dist/index.js`

```js
function backSlash(path2) {
  return path2.replace(/\//g, import_path4.sep);
}
```

**Comment by peterroe** [comment]
Still got the same error  :(

**Comment by userquin** [comment]
@peterroe can you provide a minimal repro?

**Comment by aliuq** [comment]
> @peterroe can you provide a minimal repro?

[`vue-cli`](https://github.com/unocss/unocss/tree/main/examples/vue-cli) example  has same issue in windows WSL, maybe it exists in linux

**Comment by peterroe** [comment]
OK，I try to minimize it, but it takes some time. This is my origin repo : https://github.com/peterroe/Rss-Reader

**Comment by peterroe** [comment]
I have been developing on `windows` system before, and this error occurred after trying to work with `macbook`

**Comment by userquin** [comment]
@peterroe try `import 'virtual:uno.css'` or `import 'unocss'`

**Comment by peterroe** [comment]
```shell
Syntax Error: Reading from "virtual:uno.css" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
```
webpack doesn't seem to support it

**Comment by userquin** [comment]
@peterroe so in Windows still working or the same error with your repro? can you send the full stacktrace here userquin@gmail.com?

**Comment by aliuq** [comment]
> Still got the same error :(



> > No，Macbook pro
> 
> Try to modify `backSlash` function in `node_modules/unplugin/dist/index.js`
> 
> ```js
> function backSlash(path2) {
>   return path2.replace(/[\\/]/g, import_path4.sep);
> }
> ```

@peterroe  modified it exist this error?

**Comment by userquin** [comment]
> @peterroe modified it exist this error?

this should work, I'm on Windows machine so I haven't that problem, the unocss works

**Comment by aliuq** [comment]
> > @peterroe modified it exist this error?
> 
> this should work, I'm on Windows machine so I haven't that problem, the unocss works

ion linux(WSL), I met the same error, after temporarily modifed, it works on windows and linux

**Comment by userquin** [comment]
@aliuq we should file a bug on `unplugin`

**Comment by userquin** [comment]
@peterroe fixed upstream, next release should update unplugin version to 0.6.3 and should fix this issue, I'll close it when updated, you'll only need to update unocss

**Comment by peterroe** [comment]
I try to upgrade `unocss`. But still can't solve this problem
```shell
"unocss": "^0.33.1"
```

stacktrace:

```shell
ERROR in ./_virtual_\__uno.css 4:14-362
Module not found: Error: Can't resolve '../_virtual_/__uno.css' in '/MyProject/_virtual_\'
```

**Comment by peterroe** [comment]
> > Still got the same error :(
> 
> > > No，Macbook pro
> > 
> > 
> > Try to modify `backSlash` function in `node_modules/unplugin/dist/index.js`
> > ```js
> > function backSlash(path2) {
> >   return path2.replace(/[\\/]/g, import_path4.sep);
> > }
> > ```
> 
> @peterroe modified it exist this error?

I tried to modify it like you said. But still got the same error

**Comment by peterroe** [comment]
And I upgrade `unocss` to `0.33.1`, ...same error :(

**Comment by userquin** [comment]
@peterroe you will need to delete `node_modules` and make a fresh install, or await to release a new version with the unplugin version updated...

**Comment by userquin** [comment]
webpack dep is still using `0.6.2` and we need `0.6.3`: https://github.com/unocss/unocss/blob/main/packages/webpack/package.json#L46

**Comment by peterroe** [comment]
OK. Thanks.👌

**Comment by userquin** [comment]
> OK. Thanks.👌

check this, it seems it is working but wait to new release if you don't want to remove your `node_modules`: https://github.com/unocss/unocss/issues/797

**Comment by userquin** [comment]
@peterroe you need to update `@unocss/webpack` not `unocss`

**Comment by peterroe** [comment]
> @peterroe you need to update also `@unocss/webpack` not only `unocss`

Thank your help. Finally I succeeded😊.I think there are two reasons why my use of `unocss` fails:

* `backSlash`
* `yarn`

I update my `unocss` dep✅, and I switch `yarn` to `pnpm`✅. 

I don't know why `yarn` also has problems
